<!DOCTYPE html>
<html class="no-js">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <title>Visualizing box office revenue by genre  &middot; rdata.lu - Specialized in data science training and expertise</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="HandheldFriendly" content="True">
<meta name="MobileOptimized" content="320">
<meta name="viewport" content="width=device-width, initial-scale=1">


<meta name="description" content="I love going to the cinema don&#39;t you? But I also like playing with data. Hence, I will show you how we can link these 2 elements by making a nice treemap using R." />

<meta name="keywords" content="ggplot2, web-data, cinema, ">


<meta property="og:title" content="Visualizing box office revenue by genre  &middot; rdata.lu - Specialized in data science training and expertise ">
<meta property="og:site_name" content="rdata.lu - Specialized in data science training and expertise"/>
<meta property="og:url" content="/post/2017-12-04-visualizing-box-office-revenue-by-genre/" />
<meta property="og:locale" content="en-us">


<meta property="og:type" content="article" />
<meta property="og:description" content="I love going to the cinema don&#39;t you? But I also like playing with data. Hence, I will show you how we can link these 2 elements by making a nice treemap using R."/>
<meta property="og:article:published_time" content="2017-12-04T06:34:55&#43;02:00" />
<meta property="og:article:modified_time" content="2017-12-04T06:34:55&#43;02:00" />

  
    
<meta property="og:article:tag" content="ggplot2">
    
<meta property="og:article:tag" content="web-data">
    
<meta property="og:article:tag" content="cinema">
    
  

  
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@" />
<meta name="twitter:creator" content="@" />
<meta name="twitter:title" content="Visualizing box office revenue by genre" />
<meta name="twitter:description" content="I love going to the cinema don&#39;t you? But I also like playing with data. Hence, I will show you how we can link these 2 elements by making a nice treemap using R." />
<meta name="twitter:url" content="/post/2017-12-04-visualizing-box-office-revenue-by-genre/" />
<meta name="twitter:domain" content="/">
  

<script type="application/ld+json">
  {
    "@context": "http://schema.org",
    "@type": "Article",
    "headline": "Visualizing box office revenue by genre",
    "author": {
      "@type": "Person",
      "name": "http://profiles.google.com/+?rel=author"
    },
    "datePublished": "2017-12-04",
    "description": "I love going to the cinema don&#39;t you? But I also like playing with data. Hence, I will show you how we can link these 2 elements by making a nice treemap using R.",
    "wordCount": 1824
  }
</script>



<link rel="canonical" href="/post/2017-12-04-visualizing-box-office-revenue-by-genre/" />

<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/touch-icon-144-precomposed.png">
<link href="/favicon.png" rel="icon">

<meta name="generator" content="Hugo 0.29" />

  <meta name="description" content="The purpose of this blog is to share our R knowledge with some tips that have been useful for our own data analysis. Most posts use public
  data that have been scraped using R or Python." />
  <link rel="stylesheet" href="/assets/css/bootstrap.min.css">
  <link rel="stylesheet" href="/assets/css/font-awesome.min.css">
  <link rel="stylesheet" href="/assets/css/style.css">
  <link rel="stylesheet" href="/assets/css/tomorrow-night.css">
  <link href='//fonts.googleapis.com/css?family=Source+Code+Pro' rel='stylesheet' type='text/css'>

</head>
<body class="bg-light">
    <link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">
<link rel="shortcut icon" href="/img/favicon.png">
<nav class="navbar navbar-expand-md navbar-light blog-header">
  <div class="container contt">
    <a class="navbar-brand" href="http://www.rdata.lu/"><span class="red">r</span>Data<span class="blue">.lu</span> 
      
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#exCollapsingNavbar2"
        aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
      &#9776;
    </button>
    <div class="collapse navbar-collapse" id="exCollapsingNavbar2">

      <ul class="nav navbar-nav">

        <li class="pull-xs-right">
        
        
          <li class="nav-item ">
          <a class="nav-link menu-item" href="/">
              <i class='fa fa-home'></i>
              <span>HOME</span>
          </a>
        </li>

        
          <li class="nav-item ">
          <a class="nav-link menu-item" href="/page/visualization">
              <i class='fa fa-pie-chart'></i>
              <span>VISUALIZATION</span>
          </a>
        </li>

        
          <li class="nav-item ">
          <a class="nav-link menu-item" href="/categories/">
              <i class='fa fa-folder-open'></i>
              <span>CATEGORIES</span>
          </a>
        </li>

        
          <li class="nav-item ">
          <a class="nav-link menu-item" href="/page/contact">
              <i class='fa fa-info-circle'></i>
              <span>CONTACT</span>
          </a>
        </li>

        
        </li>
      </ul>
    </div>
  </div>
</nav>


<div class="container p-a-0 large">
  <div class="row m-l-0 m-r-0">
    <div class="col-xs-12 col-md-12 post-container">
      <div>
  
<a href="/post/2017-12-04-visualizing-box-office-revenue-by-genre/" itemprop="url">
    
      <img src="/images/cinema500.svg" class="img-fluid" alt="Generic responsive image">
    
</a>

<div class="container">
    <div class="row">
        <div class="col-12 name" >
    <img id="avatar" src="/images/logo.png" />
    
       by Kevin Rosamont
    
        </div>
        
    </div>
    </div>

  <div class="container">
    <div class="col-xs-12 col-sm-12 col-md-10 col-lg-10">
      <h1 class="post-title cat" >Visualizing box office revenue by genre
</h1>
    </div>
  </div>

  <div class="container">
    <div class="col-xs-12 col-sm-12 col-md-10 col-lg-10">
      <div class="post-meta">
      <div class="post-meta-item">
        <i class="fa fa-calendar"></i>
        <time datetime="2017-12-04">4 Dec, 2017</time>
      </div>
      <div class="row itemHome">
        
            
            
            <div class="post-meta-item">
                <i class="fa fa-folder-open-o"></i>
                
                <a class="article-category-link" href="/categories/visualization">Visualization</a>
                
                
            </div>
            
        

        
            
            
              <div class="post-meta-item">
                <i class="fa fa-tags"></i>
                
                <a href="/tags/ggplot2/">ggplot2</a>
                &middot;
                
                <a href="/tags/web-data/">web-data</a>
                &middot;
                
                <a href="/tags/cinema/">cinema</a>
                
                
              </div>
            
        

      </div>



      <div class="row itemHome">
         9 Minute Read
         1824 Words
        
        <div class="post-meta-item">
          &nbsp;<i class="fa fa-comment-o"></i>
          <a href="/post/2017-12-04-visualizing-box-office-revenue-by-genre/#disqus_thread" class="article-comment-link">
               Comments
          </a>
        </div>
        

      </div>


    </div>
    </div>
  </div>

</div>

      <div class="content">
  <div class="container">
    <div class="col-xs-12 col-sm-12 col-md-10 col-lg-10">
      <p>After having watched Justice League in cinema, I was impressed by all of the special effects and how good they were. I started wondering myself: How much does a movie like that cost? And most importantly, how big is the box-office revenue for this kind of blockbuster? I found an answer in <a href="http://www.the-numbers.com/movie/budgets/all">The Numbers</a>. I have then decided to make a database from the data available on this website. I have retrieved the 500th biggest movie budgets. Initially I just had a database with 5 variables on movies:<br> • the release date<br> • the name <br> • the production budget <br> • the dosmestic gross <br> • the worldwide gross <br> Thereafter, I crossed sources to get more variables. Data was scrapped on Wikipedia and IMDb. We finally get a dataset with 30 variables such as lists of actors, affiches url, distributions, rate and the number of raters from IMDb , etc…<br> You can find a complete description of the dataset on <a href="https://github.com/krosamont/Cinema">GitHub</a>. All the data was scrapped via the package <code>rvest</code>.<br><br></p>
<p>In this post, I describe the different steps leading to the treemap: <br></p>
<div id="tmp1" class="tmap">

</div>
<div id="starting-point" class="section level1">
<h1>STARTING POINT</h1>
<p>First of all we read the data.</p>
<pre class="r"><code>db = read.csv(&quot;https://cdn.rawgit.com/krosamont/Cinema/dd7eca65/moviedb500.csv&quot;,
              stringsAsFactors = FALSE)
#You can excecute the following line to have more information about the variable type.
#str(db) </code></pre>
<p>Then we want to transform variables related to money in numeric variables and the movie realease dates in date variable using <code>tidyverse</code>.</p>
<pre class="r"><code>library(tidyverse)

db = db %&gt;%
        mutate( Release.Date = as.Date(Release.Date, &quot;%m/%d/%Y&quot;), 
                Running.time = as.numeric(stringr::str_sub(Running.time,1,3)),
                Rate = as.numeric(Rate),
                Raters = as.numeric(gsub(&quot;,&quot;, &quot;&quot;, Raters)),
                Production.Budget = as.numeric(gsub(&quot;[,$]&quot;, &quot;&quot;,
                                                 Production.Budget)),
                Domestic.Gross = as.numeric(gsub(&quot;[,$]&quot;, &quot;&quot;,
                                                 Domestic.Gross)),
                Worldwide.Gross = as.numeric(gsub(&quot;[,$]&quot;, &quot;&quot;,
                                                 Worldwide.Gross)) ) %&gt;%
        arrange(desc(Worldwide.Gross))</code></pre>
<p>The dataset looks better. As you have seen on top of this post. We want to design a treemap chart to visualize box-office revenue by genre. Let’s see how many movie genres are present in the data frame:</p>
<pre class="r"><code>UniqueGenres = unique(db$Genres)
length(UniqueGenres)</code></pre>
<pre><code>## [1] 224</code></pre>
<pre class="r"><code>head(UniqueGenres, 5)</code></pre>
<pre><code>## [1] &quot;Action Adventure Fantasy Sci-Fi&quot;                  
## [2] &quot;Action Adventure Sci-Fi&quot;                          
## [3] &quot;Action Crime Thriller&quot;                            
## [4] &quot;Adventure Drama Fantasy Mystery&quot;                  
## [5] &quot;Animation Adventure Comedy Family Fantasy Musical&quot;</code></pre>
<p>There are 224 combinations of genres, which is way too many combinations. We need to reduce them in a way that each movie has 2 genres at the most: A main genre and a subgenre.</p>
</div>
<div id="main-genres" class="section level1">
<h1>MAIN GENRES</h1>
<p>Let’s start with a simple barplot to visualize the most-represented genre from the 224 combinations.</p>
<pre class="r"><code>library(ggthemes)

all_genres = separate_rows(db %&gt;% 
                           group_by(Genres) %&gt;% 
                           select(Genres) %&gt;% 
                           filter(row_number() ==1),
                           Genres, sep=&quot;[[:space:]]&quot;)

name_order = names(sort(table(all_genres)))

ggplot(all_genres, aes(Genres)) +
                theme_minimal( ) + 
        geom_bar( stat = &quot;count&quot;, fill=&quot;#007acc&quot; ) +
        coord_flip() +
        scale_x_discrete(limits = name_order)</code></pre>
<p><img src="/post/2017-12-04-visualizing-box-office-revenue-by-genre_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>We see that Adventure and Action are the most important genres, followed by those between Comedy and Sci-fi. The genres that come after Sci-fi are present in less than 60 combinations of genres. Hence we will consider them as subgenres. We have 8 main genres: <br> • Adventure <br> • Action <br> • Comedy <br> • Drama <br> • Family <br> • <del>Fantasy</del> <br> • Thriller <br> • <del>Sci-Fi</del> <br> But we also know that Sci-Fi and Fantasy can be seen as subgenres from Adventure or Action. Therefore, we finally keep 6 genres. <br> We have to check that all movies can have a main genre from the 6 genres that we have choosen. For that, we simply check that each combination have at least one of the main genre :</p>
<pre class="r"><code>mainGenres= paste(c(&quot;Adventure&quot;, &quot;Action&quot;,  &quot;Comedy&quot;, 
                    &quot;Drama&quot;, &quot;Family&quot;, &quot;Thriller&quot;),
                  collapse=&quot;|&quot;)

# grepl returns true for each genre combination if at least one of the main genre is present
length(grepl(mainGenres, db$Genres))/length(db$Genres)</code></pre>
<pre><code>## [1] 1</code></pre>
<p>Apparently, this is the case :)</p>
<div id="first-reduction" class="section level3">
<h3>FIRST REDUCTION</h3>
<p>We finally add a main genre to all movies.<br> <strong>Be careful, The main genre of each movie will depend on the order in which you attribute the main genre. So the final shape of the output will depend on this step.</strong></p>
<pre class="r"><code>#1
db$Genresl1=ifelse(grepl(&quot;Family&quot;,db$Genres),
                   &quot;Family&quot;, db$Genres)

#2
db$Genresl1=ifelse(grepl(&quot;Drama&quot;, db$Genresl1),
                   &quot;Drama&quot;, db$Genresl1)

#3
db$Genresl1=ifelse( grepl(&quot;Thriller&quot;, db$Genresl1),
                    &quot;Thriller&quot;, db$Genresl1)

#4
db$Genresl1=ifelse(grepl(&quot;Action&quot;, db$Genresl1),
                   &quot;Action&quot;, db$Genresl1)

#5
db$Genresl1 =ifelse(grepl(&quot;Adventure&quot;, db$Genresl1),
                    &quot;Adventure&quot;, db$Genresl1)

#6
db$Genresl1=ifelse(grepl(&quot;Comedy&quot;, db$Genresl1),
                   &quot;Comedy&quot;, db$Genresl1)</code></pre>
<p>Now that the main genre were attributed, let’s focus on the subgenre.</p>
</div>
</div>
<div id="subgenres" class="section level1">
<h1>SUBGENRES</h1>
<p>We have seen that only 6 genres could be considered as main genres. However, in this part we will consider that all genres can be considered as subgenres. Now one of the difficulties is to decide which subgenre to select when there is more than one option. Association rules can help us in this task. We can see which subgenres are the most present for each genre and their level of dependency.</p>
<div id="association-rules" class="section level2">
<h2>ASSOCIATION RULES</h2>
<p>Let’s analyze the different genre combinations through an association rule analysis. We need first to read data as transaction. For that we use the package <code>arules</code>.</p>
<pre class="r"><code>library(arules)
#no duplicate combinations!
item_genres = read.transactions(&quot;https://cdn.rawgit.com/krosamont/Cinema/dd7eca65/itemGenres.csv&quot;,
                                format = &quot;basket&quot;, sep=&quot;:&quot;)</code></pre>
<p>In this post, we will focus ourselves on 2 association rule indicators: <strong>the support</strong> and <strong>the confidence</strong>. <br> Support and confidence are displayed like the result bellow when the function <code>arules::rules</code> is used. <br></p>
<pre><code>##     lhs              rhs      support     confidence lift     count
## [1] {Documentary} =&gt; {Drama}  0.004444444 1.0000000  2.777778  1   
## [2] {War}         =&gt; {Drama}  0.057777778 0.9285714  2.579365 13   
## [3] {History}     =&gt; {Drama}  0.080000000 0.9473684  2.631579 18   
## [4] {Animation}   =&gt; {Family} 0.208888889 0.9591837  2.731852 47</code></pre>
<p>• <strong>Support</strong> indicates how frequently genres in columns lhs and rhs appear together in the 224 combinations. The first row of the result above means that War and Drama appear together in 5,78% of combinations.</p>
<p>• <strong>Confidence</strong> is an indication of how often the rule has been found to be true. It can also be seen as a conditional probability. { X =&gt; Y } means P(Y | X). This is the probability that the genre Y is also present when we already know that genre X is present. { War =&gt; Drama } = 0.929 from the second line of the result above means that Drama will be present in 92,9% of combination where War is present.<br> <strong>But be carefull, this relation is not neccesarly true in the opposite direction!</strong></p>
<p>To see all association rules starting from a confidence level of 30% between 2 genres we write: <br></p>
<pre class="r"><code>rules = apriori(item_genres, 
                parameter=list(support=(1/nrow(item_genres)), 
                confidence=0.3, minlen=2, maxlen=2)  )
ins_rules = inspect(rules) 

ins_rules</code></pre>
<p>If we want to focus on the relationship between subgenres and main genres, we can filter the rhs columns.</p>
<pre class="r"><code>mainGenres = unlist(strsplit(mainGenres, &quot;|&quot;, fixed = TRUE))
ins_rules = ins_rules %&gt;% 
        #removing the arrow =&gt;
        .[,-2] %&gt;%
        #removing the brackets for both columns, lhs and rhs
        mutate(lhs = trimws(gsub(&quot;\\{|\\}&quot;,&quot;&quot;,lhs)),
               rhs = trimws(gsub(&quot;\\{|\\}&quot;,&quot;&quot;,rhs))) %&gt;%
        filter(rhs %in% mainGenres) %&gt;%
        group_by(lhs) %&gt;%
        filter(row_number() == 3) %&gt;%
        arrange(lhs, desc(confidence))

ins_rules</code></pre>
<pre><code>## # A tibble: 17 x 6
## # Groups:   lhs [17]
##          lhs       rhs    support confidence      lift count
##        &lt;chr&gt;     &lt;chr&gt;      &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;
##  1 Adventure    Action 0.29333333  0.5739130 1.1739130    66
##  2 Animation Adventure 0.16888889  0.7755102 1.5173026    38
##  3 Biography Adventure 0.01333333  0.3333333 0.6521739     3
##  4    Comedy Adventure 0.18666667  0.5121951 1.0021209    42
##  5     Crime    Comedy 0.04888889  0.3548387 0.9736428    11
##  6     Drama Adventure 0.13333333  0.3703704 0.7246377    30
##  7    Family Adventure 0.24888889  0.7088608 1.3869015    56
##  8   Fantasy    Action 0.12888889  0.3866667 0.7909091    29
##  9   History Adventure 0.03555556  0.4210526 0.8237986     8
## 10   Musical    Family 0.06222222  0.8750000 2.4920886    14
## 11   Mystery Adventure 0.06666667  0.5000000 0.9782609    15
## 12   Romance    Family 0.05333333  0.3000000 0.8544304    12
## 13    Sci-Fi    Family 0.08888889  0.3125000 0.8900316    20
## 14     Sport    Family 0.02222222  0.5000000 1.4240506     5
## 15  Thriller Adventure 0.13777778  0.4305556 0.8423913    31
## 16       War Adventure 0.02222222  0.3571429 0.6987578     5
## 17   Western Adventure 0.02222222  0.6250000 1.2228261     5</code></pre>
<div id="barplot" class="section level3">
<h3>BARPLOT</h3>
<p>We create a new variable that we named: <code>withoutMainGenres</code>. This variable is the combination of genres without the main genre. If a movie has the combination: “Drama War Action Biography” and his main genre is “Drama”, then value of <code>withoutMainGenres</code> will be “War Action Biography”. If it’s not clear enough, I suggest that you run the code and to compare the variables <code>withoutMainGenres</code> and <code>Genres</code>. Once this new variable is made, we draw again a barplot to see the ditribution of genres.</p>
<pre class="r"><code>db$withoutMainGenres = trimws(mapply(gsub, db$Genresl1, &quot;&quot;, db$Genres))

all_genres = separate_rows(db %&gt;% 
                           group_by(withoutMainGenres) %&gt;% 
                           select(withoutMainGenres) %&gt;% 
                           filter(row_number() ==1),
                           withoutMainGenres, 
                           sep=&quot;[[:space:]]&quot;) %&gt;% 
             rename( Genres=withoutMainGenres) %&gt;%
             filter(nchar(Genres)&gt;0)

name_order = names(sort(table(all_genres)))

ggplot(all_genres, aes(Genres)) +
                theme_minimal( ) + 
        geom_bar( stat = &quot;count&quot;, fill=&quot;#007acc&quot; ) +
        coord_flip() +
        scale_x_discrete(limits = name_order)</code></pre>
<p><img src="/post/2017-12-04-visualizing-box-office-revenue-by-genre_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>We see that there are still a lot of adventure movies. We use the result seen in the association rules and the barplot to make the subgenres.<br> We begin with the genre Animation because we want to regroup all of these movies in the same category. Then we add subgenres in an ascending order, from the less important to the most one.<br> However, movies from musical, music and horror genres are added at the end of the script because the attribution of these genres for the movie in our dataset is questionable.</p>
<pre class="r"><code>db$Genresl2=ifelse(grepl(&quot;Animation&quot;,db$withoutMainGenres), 
                   &quot;Animation&quot;, db$withoutMainGenres)
db$Genresl2=ifelse(grepl(&quot;Documentary&quot;,db$Genresl2),
                   &quot;Documentary&quot;, db$Genresl2)
db$Genresl2=ifelse(grepl(&quot;Biography&quot;, db$Genresl2), 
                   &quot;Biography&quot;, db$Genresl2)
db$Genresl2=ifelse(grepl(&quot;Western&quot;,db$Genresl2), 
                   &quot;Western&quot;, db$Genresl2)
db$Genresl2=ifelse(grepl(&quot;Sport&quot;,db$Genresl2), 
                   &quot;Sport&quot;, db$Genresl2)
db$Genresl2=ifelse(grepl(&quot;War&quot;,db$Genresl2), 
                   &quot;War&quot;, db$Genresl2)
db$Genresl2=ifelse(grepl(&quot;Mystery&quot;,db$Genresl2), 
                   &quot;Mystery&quot;, db$Genresl2)
db$Genresl2=ifelse(grepl(&quot;Romance&quot;,db$Genresl2), 
                   &quot;Romance&quot;, db$Genresl2)
db$Genresl2=ifelse(grepl(&quot;Crime&quot;,db$Genresl2), 
                   &quot;Crime&quot;, db$Genresl2)
db$Genresl2=ifelse(grepl(&quot;Drama&quot;,db$Genresl2), 
                   &quot;Drama&quot;, db$Genresl2)
db$Genresl2=ifelse(grepl(&quot;Fantasy&quot;,db$Genresl2), 
                   &quot;Fantasy&quot;, db$Genresl2)
db$Genresl2=ifelse(grepl(&quot;Sci-Fi&quot;,db$Genresl2), 
                   &quot;Sci-Fi&quot;, db$Genresl2)
db$Genresl2=ifelse(grepl(&quot;Comedy&quot;,db$Genresl2), 
                   &quot;Comedy&quot;, db$Genresl2)
db$Genresl2=ifelse(grepl(&quot;Thriller&quot;,db$Genresl2), 
                   &quot;Thriller&quot;, db$Genresl2)
db$Genresl2=ifelse(grepl(&quot;Adventure&quot;,db$Genresl2), 
                   &quot;Adventure&quot;, db$Genresl2)
db$Genresl2=ifelse(grepl(&quot;Musical&quot;,db$Genresl2), 
                   &quot;Musical&quot;, db$Genresl2)
db$Genresl2=ifelse(grepl(&quot;Music&quot;,db$Genresl2), 
                   &quot;Music&quot;, db$Genresl2)
db$Genresl2=ifelse(grepl(&quot;Horror&quot;,db$Genresl2), 
                   &quot;Horror&quot;, db$Genresl2)
db$Genresl2=ifelse(db$Genresl2==&quot;&quot;,
                   db$Genresl1, db$Genresl2)</code></pre>
<p>Now that we have our 2 levels of genres. We can build our treemap!</p>
</div>
</div>
</div>
<div id="treemap-with-treemapify" class="section level1">
<h1>TREEMAP WITH TREEMAPIFY</h1>
<p>To design the treemap, we need to regroup movies by main genres and subgenres, then we sum their Worlwide Gross revenue.</p>
<pre class="r"><code>summary.Genre = db %&gt;%
        group_by(Genresl1, Genresl2) %&gt;%
        summarise(Sum_Gross = sum(Worldwide.Gross))</code></pre>
<p>Finally we design the treemap using <code>ggplot2</code> and <code>treemapify</code>:</p>
<pre class="r"><code>library(treemapify)

ggplot(summary.Genre, aes(area = Sum_Gross ,
                          fill = Genresl1, label = Genresl2,
                          subgroup =Genresl1)) +
        geom_treemap() +
        geom_treemap_subgroup_border() +
        geom_treemap_subgroup_text(place = &quot;centre&quot;, 
                                   grow = T, 
                                   alpha = 0.5, 
                                   colour = &quot;black&quot;, 
                                   fontface = &quot;italic&quot;, 
                                   min.size = 0) +
        geom_treemap_text(colour = &quot;white&quot;, 
                          place = &quot;topleft&quot;, 
                          reflow = T)</code></pre>
<p><img src="/post/2017-12-04-visualizing-box-office-revenue-by-genre_files/figure-html/unnamed-chunk-18-1.png" width="672" /> <br></p>
<p>Here we have a first result but we can do better by adding some interactivity.</p>
</div>
<div id="treemap-with-highcharter" class="section level1">
<h1>TREEMAP WITH HIGHCHARTER</h1>
<p>Let’s add some interactivity using the package <code>highcharter</code>. We use the github version (there are more functions).</p>
<pre class="r"><code>devtools::install_github(&quot;jbkunst/highcharter&quot;)

library(highcharter)
hctreemap2(data = db,
           group_vars = c(&quot;Genresl1&quot;, &quot;Genresl2&quot;),
           size_var = &quot;Worlwide.Gross&quot;,
           color_var = &quot;Genresl2&quot;,
           layoutAlgorithm = &quot;squarified&quot;,
           levelIsConstant = FALSE,
           levels = list(
                   list(level = 1, 
                        dataLabels = list(enabled = TRUE)),
                   list(level = 2, 
                        dataLabels = list(enabled = FALSE))
           )) %&gt;% 
        hc_tooltip(pointFormat = &quot;&lt;b&gt;{point.name}&lt;/b&gt;:&lt;br&gt;
                   Worlwide Gross: $ {point.value:,.0f}&quot;)</code></pre>
<p>The following error message appears:<br> <font color="red"><strong>Error in hctreemap2(data = db, group_vars = c(“Genresl1”, “Genresl2”) :<br> Treemap data uses same label at multiple levels.</strong> </font><br></p>
<p>We can’t design a 2 levels treemap with <code>highcharter</code> because main genres and subgenres share some genres. Hence, R is a great tool for data manipulation but javascript is a better tool for visualization. <br></p>
<p>We can easily design a 2 levels responsive treemap with the library <a href="https://www.highcharts.com/">highchart</a> in javascript.</p>
<div id="tmp2" class="tmap">

</div>
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
  integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
  crossorigin="anonymous"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/treemap.js"></script>
<script src="https://cdn.rawgit.com/krosamont/Cinema/dd7eca65/treemap/js/cinemaTreemap.js"></script>
<p><link rel="stylesheet" href="https://cdn.rawgit.com/krosamont/Cinema/dd7eca65/treemap/css/styleSheet.css"></p>
<p>
Don’t hesitate to follow us on twitter <a href="https://twitter.com/rdata_lu" target="_blank"><span class="citation">@rdata_lu</span></a> <!-- or <a href="https://twitter.com/brodriguesco">@brodriguesco</a> --> and to <a href="https://www.youtube.com/channel/UCbazvBnJd7CJ4WnTL6BI6qw?sub_confirmation=1" target="_blank">subscribe</a> to our youtube channel. <br> You can also contact us if you have any comments or suggestions. See you for the next post!
</p>
</div>

    </div>
  </div>
</div>

      <footer>
    
    
      
      <div class="container">
        <div class="col-xs-12 col-sm-12 col-md-10 col-lg-10">
          <nav><ul class="pagination pagination-article">
          
              <li class="page-item">
                <a href="/post/2017-11-14-functional-peace-of-mind/" title="Functional peace of mind " class="page-link">
                  <span aria-hidden="true">&larr;</span>Previous
                </a>
              </li>
          

          
            <li class="page-item">
              <a href="/post/2017-12-21-skip-errors-in-r-by-not-writing-loops/" title="Skip errors in R loops by not writing loops" class="page-link">
                  Next <span aria-hidden="true">&rarr;</span>
              </a>
            </li>
          
          </ul> </nav>
        </div>
      </div>

      
    

  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    
    <div id="disqus_thread"></div>
    <script type="text/javascript">
      (function() {
        
        
        if (window.location.hostname == "localhost")
          return;

        var dsq = document.createElement('script'); dsq.async = true; dsq.type = 'text/javascript';
        dsq.src = '//wooza.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
      })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    
  </div>
</footer>

    </div>
      
  </div>
</div>
      <footer class="footer hidden-print">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-9">
        <p class="text-xs-center m-a-0 p-a-0">
          &copy; 2018 Copyright &copy; rdata.lu. All rights reserved. <br> Content reblogged by <a href='https://www.r-bloggers.com/' target='_blank'>R-bloggers</a>
        </p>
        <p class="text-xs-center  m-a-0 p-a-0">
            
          <span class="p-l-1 p-r-1">
                <a href="/page/disclaimer/"> </a>
              </span>
                
        </p>

      </div>
    </div>
  </div>
</footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.10.8/umd/popper.min.js" integrity="sha256-n96swYoYKdVyLr5XatK9CzcdyrpAI0xcSlIeWOZeTAI=" crossorigin="anonymous"></script>

<script src="/assets/js/bootstrap.min.js"></script>
<script src="/assets/js/highlight.pack.js"></script>

<script>hljs.initHighlightingOnLoad();</script>


<script id="dsq-count-scr" src="//wooza.disqus.com/count.js" async></script>




<script type="text/javascript" src="/assets/js/script.js"></script>


<script>
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
ga('create', 'UA-111615540-1', 'auto');
ga('send', 'pageview');
</script>
<script async src='//www.google-analytics.com/analytics.js'></script>


  </body>
</html>

